// LA DESESTRUCTURACION DE ARREGLOS EN JSON, ES UNA CARACTERISTICAS QUE TE PERMITE EXTRAER VALORES DE UN ARREGLO Y ASIGNARLOS A VARIABLES/CONSTANTES INDIVIDUALES DE UNA MANERA MAS CONVENIENTE.

// aSIGNACION DE VALORES A VARIABLES INDIVIDUALES
const arreglo =[1,2,3]

// DESESTRUCTURACION
let[primerValor, segundoValor, tercerValor] = arreglo

console.log(segundoValor);